### ISSUE TITLE
[Request] Add an option to Copy Link Domain

### ISSUE THREAD

**Issue by Jeeva-Raam** [Yukisama/TextLinkyTool#10]
Please add an option to copy only the domain name.

**Eg**: from link 

> **https:\/\/github.com/Yukisama/TextLinkyTool**

 only to copy 

> **https:\/\/github.com**

 or 

> **github.com**

**Comment by Yukisama** [comment]
Hi,

"[[url]]" format get "https://github.com/Yukisama/TextLinkyTool" in past version.
At the new version :
use "[[fullhost]]" format to get "https://github.com" ,
and "[[host]]" format to get "github.com" .

The new format available now.
Please upgrade TextLinkyTool to version 1.2.7 and enjoy it.
Thank you for your suggestion.

**Comment by Yukisama** [comment]
No response over 7 day.
Issue close.
