### ISSUE TITLE
[Request] List links only

### ISSUE THREAD

**Issue by olivierberten** [Yukisama/TextLinkyTool#11]
Please add an option to copy all and only the links in a page. Currently, the only way to copy links is to copy all urls, which includes all images, scripts, stylesheets, etc. It would be great if it was possible to copy only the hrefs!

**Comment by Yukisama** [comment]
Hi,
"Text Linky Tool"  is "analyze Text and find Links Tool"
The feature "Filter links only" not be implemented  in the short term.
May you please try the other extensions like "Snap Links Plus". ( https://addons.mozilla.org/addon/snaplinksplus/ )
I believe you will be satisfied.
Thanks your feedback. good luck.
