### ISSUE TITLE
feature: paste page title/url into WYSIWYG editor

### ISSUE THREAD

**Issue by atomGit** [Yukisama/TextLinkyTool#15]
with [Easy Copy](https://addons.mozilla.org/en-US/firefox/addon/easy-copy/) one could copy a page title and url and paste it into a WYSIWYG editor like TinyMCE and the result would a hyperlink with the page title

with TLT this is not the case because TinyMCE (or perhaps WordPress) is converting `<, >` to `&lt;, &gt;` in the source code (the text version of the editor)

so far i am unable to find something to replace Easy Copy (all have the same problem as above) and i really miss that capability but EC no longer works properly for me

**Comment by Yukisama** [comment]
Hi,
If you want to copy HTML Hyperlink format, TextLinkyTool allow setting custom format.
step1. Go to Text Linky Tool options page.
Step2. Find out copy tab feature, and click add format button.
Step3. Fill "Hyperlink" in name column, and fill "&lt;a href="[[url]]"&gt;[[name]]&lt;/a&gt;" in format column.
Step4. click save setting.
Step5. use it. ( copy to Hyerlink format )

**Comment by atomGit** [comment]
i already created the template - the problem is that, when i paste the hyperlink into the Wordpress visual editor (TinyMCE), it doesn't paste it as a hyperlink because it converts` <, > to &lt;, &gt; `in the source code (the text version of the editor)

**Comment by Yukisama** [comment]
Hi,
copy HTML Hyperlink format text , you should patse on HTML source code area.
if you paste <, > text to result area, the editor souce code convert to  &lt;, &gt; is corratly.

**Comment by atomGit** [comment]
yes, that is one way to do it - my point though was that, with Easy Copy, i could paste a hyperlink in the visual editor - i was wondering if you could look at the Easy Copy source code and see how they did this, and then maybe incorporate the same functionality into your add-on

**Comment by Yukisama** [comment]
I understand what you mean.
The "paste with HTML type" feature will not be implemented in "Text Linky Tool".
Because the mimetype control object type on Memory, but change mimetype will complicate all design.
I dont like to complicated addons. I would it keep "text type" for "Text Tool".
 so this feature will not be implemented.

By the way: if you want, forks one copy and change mimetype "text/plain" to "text/html" on copy actions. making a new addon with "paste HTML tpye" feature, Its easliy on github. good luck for you.

**Comment by atomGit** [comment]
thank you for the explanation - i will consider forking the code

**Comment by Yukisama** [comment]
Sorry, I made a mistake.
If you making a new addon, should use "Clone" not "Fork" on github.
Do not update new addon to this addon version tree.
Thanks for your feedback.
