### ISSUE TITLE
Extend the ability of the "copy selected urls" customization

### ISSUE THREAD

**Issue by 98gmarquee** [Yukisama/TextLinkyTool#16]
I'd like to be able to highlight a bunch of urls, the have it copy the text and url in the following format:
`[[name]][[n]][[url]][[n]][[n]]`

I'm only able to do this one link a time currently by editing or adding a custom format
![20181116-copylinks01](https://user-images.githubusercontent.com/33339926/48645694-0a39b180-e9ac-11e8-950a-210d4c011ddf.png)

I tried all the values for the "copy urls" setting, but none of them give me the text of the url:
![20181116-copylinks03](https://user-images.githubusercontent.com/33339926/48645878-a4015e80-e9ac-11e8-8c5b-e7c392e83f7d.png)

This is what I was trying to use:
![20181116-copylinks02](https://user-images.githubusercontent.com/33339926/48645892-aa8fd600-e9ac-11e8-8049-701e783f2745.png)

**Comment by Yukisama** [comment]
Hi,

This is a bug.
Analyze feature formats not apply.
I will fix it at next night.

**Comment by 98gmarquee** [comment]
I didn't realize it was a bug. Just thought it was something that could possibly be added to allow the user to copy the name/text and url for a batch of highlighted links vs just a single link.

**Comment by Yukisama** [comment]
> I didn't realize it was a bug. Just thought it was something that could possibly be added to allow the user to copy the name/text and url for a batch of highlighted links vs just a single link.

I got it. For 'link objects' and 'image objects' batch analyze will implement on later version.
Maybe the other extensions can help you now,  like "Snap Links Plus". ( https://addons.mozilla.org/addon/snaplinksplus/ )
Thanks your feedback. good luck.

**Comment by 98gmarquee** [comment]
@Yukisama I tried SNP, but it just doesn't do what I need. It only lets me copy all the links in a box as well, but doesn't capture the link and link text.

Makes me really miss the old "Multi Links" addon.

When/if you add the ability to your addon, I can finally stop using the old FF as I really need this one add on for work and I still use it daily. So I have "portable apps" installed with a really old version of FF just for "Multi Links" and one other until I can find proper alternatives.

**Comment by Yukisama** [comment]
Hyperlink objects and Image objects batch analyze will implemented.
Please update to version 1.2.11.
