### ISSUE TITLE
Text Linky Tool does not show up at addons.mozilla.org

### ISSUE THREAD

**Issue by ReporterX** [Yukisama/TextLinkyTool#19]
Firefox 66.0.2 (64-bit)
Text Linky Tool 1.2.10

It is weird Text Linky Tool does not work at https://addons.mozilla.org/

**Comment by Yukisama** [comment]
Hi,
the Mozilla security policy is not allow extensions working in "addons.mozilla.org" hosts.

**Comment by ReporterX** [comment]
I see. FoxyTab managed to make it working though.

I can still copy tab info using FoxyTab at mozilla.org.

**Comment by Yukisama** [comment]
Hi,

I dont want to get "addons.mozilla.org" host permissions.

It not to useful for users, but this extension will be reviewer looking.

so I will not add "addons.mozilla.org" host permissions.

**Comment by ReporterX** [comment]
Hi [FoxyTab](https://addons.mozilla.org/en-US/firefox/addon/foxytab/) doesn't ask for "addons.mozilla.org" host permissions. I don't know how the author managed to do though.

**Comment by Yukisama** [comment]
The Mozilla not allow inject script on at addons.mozilla.org.
If you want to run unsafe mode, you can change about:config paramters.
All extension be working on addons.mozilla.org.
and your Firefox will be danger.

**Comment by smaragdus** [comment]
Many extensions work on Firefox extensions pages, they appear in:

- Link Context Menu
- Page Context Menu
- Tab Context Menu

For **tab context menu** I found a workaround- I activate some other non-Firefox extensions tab and then I right-click on the desired Firefox extension tab and the [Text Linky Tool](https://github.com/Yukisama/TextLinkyTool) appears on **tab context menu**. But there is no workaround for **link context menu** and **page context menu**. If your extension appears on Firefox extensions pages it will be more useful so I hope that you will reconsider your decision.

**Comment by Yukisama** [comment]
You are right, but I cannot violate Mozilla policy.
