### ISSUE TITLE
be more descriptive for Copy Tab URL; for Copy Link URL; and so on

### ISSUE THREAD

**Issue by grahamperrin** [Yukisama/TextLinkyTool#2]
At https://addons.mozilla.org/addon/copy-tab-url-we/ and at https://addons.mozilla.org/addon/copy-link-url-we/ "custom format" is mysterious, ambiguous. 

Please, can you be more descriptive at those pages?

For each extension: what is the one customisation? 

Bear in mind, readers may be browsing dozens or hundreds of new extensions. The better your description, the greater the likelihood that someone will (a) understand the purpose of the extension; and then (b) be willing to install. 

Thanks

**Comment by Yukisama** [comment]
Hi,

I will try to make more descriptive at those extension.

Thank you for your consideration.

**Comment by Yukisama** [comment]
already make descriptive at extension pages.

this issue will close in 48 hours later.
