### ISSUE TITLE
[Feature request] Copy text in custom format

### ISSUE THREAD

**Issue by ReporterX** [Yukisama/TextLinkyTool#20]
I would like to have custom options to copy text in custom format.
For example, for the text: 

> This is a great day.

I want to copy it as a quote. The copy format would be:

"[[[text_in_pure_format]]" -- [[[url]]

"This is a great day." -- https://github.com/Yukisama/TextLinkyTool/issues/ 20

This feature is available in the legacy "Easy Copy" addon.

**Comment by Yukisama** [comment]
Hi,

Maybe try this setting "[[name]]"

**Comment by ReporterX** [comment]
> 
> 
> Hi,
> 
> Maybe try this setting "[[name]]"

I don't get it. Where do I put it? There is no way to configure the copy format when you just highlight and copy text.

Even if I put "[[name]]", it does not achieve what I want. [[name]] means the name of the link. What I want is the text in the paragraph that I select to copy.

**Comment by Yukisama** [comment]
Hi,

I misunderstood yesterday.

The feature "copy pure text" is not available to add format, and also it will not to enhance.
