### ISSUE TITLE
Can't select copy options

### ISSUE THREAD

**Issue by ooker777** [Yukisama/TextLinkyTool#22]
Is this dropdown the way to select which kind of copy will be applied? I want to copy tab as markdown and as HTML link, but I can't select them in here

![](https://i.imgur.com/xTFuwLq.png)

**Comment by Yukisama** [comment]
Hi,

Try call context menu on Firefox Tabs range. (not on WebPage)

**Comment by ooker777** [comment]
where is it? Do you mean this?

![](https://i.imgur.com/FDBSSm0.png)

**Comment by Yukisama** [comment]
Yes, move mouse cursor on Tabs range, then call context menu.

select "Text Link Tool" subitems , and enjoy it.

**Comment by ooker777** [comment]
Oh I get it. You mean right click on the tab:

![](https://i.imgur.com/tYVeZPB.png)

But what I'm looking for is the "Copy tab as ..." option in these dropdown menus. Is it possible?

![](https://i.imgur.com/vBFZOHG.png)

**Comment by Yukisama** [comment]
Hi,

To find "Copy Tab info - format" block at options page.

"Text Linky Tool" allow setting custom formats on copy tab info feature.

**Comment by ooker777** [comment]
I know that. I just want to have the option "Copy tab as ..." in this menu so I can use shortcut instead of mouse. 

![](https://i.imgur.com/HeaXKyG.png)

**Comment by Yukisama** [comment]
Hi,

I wnat to make this feature at shortcut, but I can not do it.

sorry for my poor ability. (☍﹏⁰)
