### ISSUE TITLE
Copy text with links

### ISSUE THREAD

**Issue by Kvain** [Yukisama/TextLinkyTool#25]
Hello!
I want to copy the selected text along with the links:
the selected text itself;
the name of the link;
URL link.
For example, here is a piece of text from a wikipedia article:

https://en.wikipedia.org/wiki/Cross-platform_software#Hardware_platforms

This is a simple copy of the text.

***
A hardware platform can refer to an instruction set architecture. For example: x86 architecture and its variants such as IA-32 and x86-64. These machines often run one version of Microsoft Windows,[5] though they can run other operating systems as well, including Linux, OpenBSD, NetBSD, macOS and FreeBSD.
***

And so I need:

***
A hardware platform can refer to an instruction set architecture https://en.wikipedia.org/wiki/Instruction_set_architecture. For example: x86 architecture and its variants such as IA-32 https://en.wikipedia.org/wiki/IA-32 and x86-64 https://en.wikipedia.org/wiki/X86-64. These machines often run one version of Microsoft Windows,[5] though they can run other operating systems as well, including Linux, OpenBSD https://en.wikipedia.org/wiki/OpenBSD, NetBSD https://en.wikipedia.org/wiki/NetBSD, macOS and FreeBSD https://en.wikipedia.org/wiki/FreeBSD.
***

How to do it? 
Thanks!

**Comment by Yukisama** [comment]
Hi,
Sorry, Text Linky Tool not to support replace features.
Should manual replace with text editor software like MSWord.
