### ISSUE TITLE
Selected text and URL

### ISSUE THREAD

**Issue by Rudi-987** [Yukisama/TextLinkyTool#26]
I really like the tool, but I'd like the option to select some text in the page and copy the selected text and the page URL to the clipboard rather than using the tab title.

**Comment by Yukisama** [comment]
Hi,
copy the selected text and the page URL can be setting to custom format.
please go to extension page, find TextLinkyTool, and open the OPTIONS page.
you can combine your favorite format, remember to Save it.
thanks for your like this extension.

**Comment by Rudi-987** [comment]
The only way that I can see to copy the text selected in the page in to select the text, then right click in the page and choose "Copy context as pure text" 
This does copy the selected text, but it does not have the option to copy the URL. If I set up a custom "Copy Tab info" there is no code for copy context info. What I am looking for is to cretae a custom action such as "[[context]][[n]]      [[url]][[n]]"    On Sunday, November 3, 2019, 08:44:32 PM CST, Yuki <notifications@github.com> wrote:  
 
 
Hi,
copy the selected text and the page URL can be setting to custom format.
please go to extension page, find TextLinkyTool, and open the OPTIONS page.
you can combine your favorite format, remember to Save it.
thanks for your like this extension.

**Comment by Yukisama** [comment]
> 
> The only way that I can see to copy the text selected in the page in to select the text, then right click in the page and choose "Copy context as pure text"  This does copy the selected text, but it does not have the option to copy the URL. If I set up a custom "Copy Tab info" there is no code for copy context info. What I am looking for is to cretae a custom action such as "[[context]][[n]]      [[url]][[n]]" On Sunday, November 3, 2019, 08:44:32 PM CST, Yuki <notifications@github.com> wrote: Hi, copy the selected text and the page URL can be setting to custom format. please go to extension page, find TextLinkyTool, and open the OPTIONS page. you can combine your favorite format, remember to Save it. thanks for your like this extension. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi,
so, you want to combined 3 actions.
1.copy Some text of pager.
2.copy page URL.
3.copy system timestamp.
but sorry, TextLinkyTools not support combined actions yet.
and will not support in the short term.

**Comment by Rudi-987** [comment]
Yuki,
Thanks for the response. Hopefully the tool will update when it is available.
    On Monday, November 11, 2019, 04:47:54 AM CST, Yuki <notifications@github.com> wrote:  
 
 

The only way that I can see to copy the text selected in the page in to select the text, then right click in the page and choose "Copy context as pure text" This does copy the selected text, but it does not have the option to copy the URL. If I set up a custom "Copy Tab info" there is no code for copy context info. What I am looking for is to cretae a custom action such as "[[context]][[n]] [[url]][[n]]" On Sunday, November 3, 2019, 08:44:32 PM CST, Yuki notifications@github.com wrote: Hi, copy the selected text and the page URL can be setting to custom format. please go to extension page, find TextLinkyTool, and open the OPTIONS page. you can combine your favorite format, remember to Save it. thanks for your like this extension. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


Hi,
so, you want to combined 3 actions.
1.copy Some text of pager.
2.copy page URL.
3.copy system timestamp.
but sorry, TextLinkyTools not support combined actions yet.
and will not support in the short term.

**Comment by Yukisama** [comment]
yes
Text tools and Linking tools are 2 separate features.
TextLinkyTools not support combined actions yet.
