### ISSUE TITLE
'Copy HTML Text' not 'Copy HTML Text WE'; 'Copy Link URL' not 'Copy Link URL WE'; 'Copy Plain Text' not 'Copy Plain Text WE'; 'Copy Tab URL' not ' Copy Tab URL WE'; and so on

### ISSUE THREAD

**Issue by grahamperrin** [Yukisama/TextLinkyTool#3]
Please consider dropping the **WE** from the names of the extensions. 

The suffixing is unnecessary, since Mozilla has significantly improved – and will continue to improve –`addons.mozilla.org`. Too many extensions are WE named, it's visual noise, a distraction, when trying to browse lists of extensions. 

Thanks

**Comment by Yukisama** [comment]
Hi,

those extesions named for "WE" is necessary now.

before Firefox ESR 59.0, legacy extesion and webapi extsion cannot be clearly identified.

I will dropping the "WE" from name after Firefox ESR 59.0 release.

Thank you for your consideration.

**Comment by grahamperrin** [comment]
Thanks!
