### ISSUE TITLE
Setting "Copy without HTML tag" not working as expected

### ISSUE THREAD

**Issue by MStrecke** [Yukisama/TextLinkyTool#31]
My goal is to copy the current state of the DOM into the clipboard by pressing a hotkey. This includes the `<HTML>` tag itself as well as the `<HEAD>` section.

I choose in the add-on settings:

`F8 - keyboard shortcut action: Copy context as HTML text`

and I unchecked:
`Copy As HTML text - Format: [ ] Copy without HTML tag`

and saved the settings.

The result is an "inner copy" of the `<BODY>` tag.

Checking the `Copy without HTML tag` settings results in the same content as `Copy context as plain text` in the shortcut section.

Am I missing something?

Thanks

**Comment by Yukisama** [comment]
Hi,

The 'Copy As HTML text ' feature just copy part of text.

not to take head tag range, full html tag range should used Firefox source viewer.
