### ISSUE TITLE
[Request] Add/delete new TextLinky

### ISSUE THREAD

**Issue by gitbees165** [Yukisama/TextLinkyTool#5]
Hello. Thanks for the useful and compact extension. In the future maybe we can have new/remove custom copy formats? Like using domainName/fullURL/baseDomainName/page description/image or link tooltip, and add custom bbcode/wiki syntax, and custom name to easily see them in context menu.

**Comment by Yukisama** [comment]
Hi,
Sounds like a good idea.
I will try to add these custom formats in the next version. (If can be used)
However, it's not easy to add custom format name, I need more time for survey browser menu  API. Maybe finished this feature in later versions.
Thank you for your feedback and suggestions.

**Comment by Yukisama** [comment]
Hi
new/remove custom copy formats  >  finished
domainName/fullURL formats  >  finished
image description  >  finished
add custom bbcode/wiki syntax  >  finished
custom name to easily see them in context menu   >  finished

I finished these features at TextLinkyTool 1.2.11 version.
enjoy it :)

**Comment by Yukisama** [comment]
Already finished.
