### ISSUE TITLE
Not working on Firefox 57.0.4 (64-bit)

### ISSUE THREAD

**Issue by shanedk** [Yukisama/TextLinkyTool#6]
The extension installs, and I see it in the right-click menu, but it doesn't actually copy the contents to the clipboard. The clipboard still has whatever it was that was in there before.

**Comment by Yukisama** [comment]
Hi
Can you reinstall the extension and try again? 
(As far as I know Firefox upgrades will cause some extensions to crash)
If the problem persists, please provide more details.
ex: target websites, features that have problems, Firefox versions and other installed extensions.
Thank you for your feedback.

**Comment by shanedk** [comment]
That didn't fix it. It doesn't work with any site. I'm running FF 57.0.4 64-bit for Windows 10, and I'm attaching a screenshot of my extensions:
![extension-list](https://user-images.githubusercontent.com/5156668/35199542-6f5a715a-fecd-11e7-9109-b674f51841e1.png)

**Comment by Yukisama** [comment]
Hi,
I tried to install the expansions of your list.
And found that "Don't Fuck With Paste" will make this issue.
I can not solve the issue caused by other extension.
You can disable "Text Linky Tool" or "Don't Fuck With Paste" one of them.
I'm sorry I can not completely solve it.
Thank you very much for your feedback.

**Comment by shanedk** [comment]
I disabled "Don't Fuck With Paste" and restarted Firefox and it still won't work.

**Comment by Yukisama** [comment]
Hi,
I have no found more problems with current information.
If it is convenient, please remove all extensions, leaving only the "Text Linky Tool",  if it still does not work, it may incompatible in a partial environment.
I need more cases to compare environment and find how it happened.

**Comment by Yukisama** [comment]
No response over 30 day. 
Issue close.
