### ISSUE TITLE
[Request] allow for column selection to highlight links

### ISSUE THREAD

**Issue by bryanl-csi** [Yukisama/TextLinkyTool#7]
On web pages where there are columns of data in a table/div that have links in them, it would be useful to be able to select just the links from a specific area vs the entire page or selection.

Multi-links used to do this, but it hasn't been ported over to the new ff yet.

I'm actually still using ff 56.0.1 just for that extension at work. I use it too much to lose it.

![2017-112-mutilinksselect](https://user-images.githubusercontent.com/883039/36492688-53e4f394-16f3-11e8-9156-024a18fb42e3.jpg)

The multi links menu:
![2017-112-mutilinksselect-leftclickmenu](https://user-images.githubusercontent.com/883039/36492755-7b87fbb2-16f3-11e8-9c34-e4451e626e77.jpg)

I use the Copy Urls With Titles option frequently.

**Comment by Yukisama** [comment]
Hi,
Select links with a rectangle will not be implemented in "Text Linky Tool".
You should try the other extensions like "Snap Links Plus". ( https://addons.mozilla.org/addon/snaplinksplus/ )
Thanks your feedback. good luck.

**Comment by Yukisama** [comment]
does not implement.

this issue will close in 24 hours later.
