### ISSUE TITLE
Copy URL of new tab should maybe copy empty string or similar?

### ISSUE THREAD

**Issue by nicolas-raoul** [Yukisama/TextLinkyTool#8]
Copy URL for new tab should copy empty string.

Very low priority.

**Comment by Yukisama** [comment]
Hi,

If Firefox open "New Tab" and the tab not refer any website, copy command be not working.

I will check this bug and try to fix it.

Thank you for your feedback.

**Comment by nicolas-raoul** [comment]
Sorry at step 9 I meant CTRL-V.
At step 8 I use the add-on on the tab where Wikipedia is already fully loaded.
I fixed the bug description.
Thanks! :-)

**Comment by Yukisama** [comment]
I checked extension and Firefox API. 
Results is "New Tab" has 2 types.
1. about:blank (New Tab) - the issue can be solve.
2. about:newtab / about:home  (New Tab) - no way to fix bug. ( Firefox Limit: https://bugzil.la/1270412 )

If your "New Tab" is type2, I am sorry that I can't solve it until Mozilla change the policy.
If your "New Tab" is type1, that's find. The new version will be updated in recent days.

**Comment by Yukisama** [comment]
new version released.

please update to v1.2.4 and enjoy it.
