### ISSUE TITLE
Not working on Firefox 57.0.4 (64-bit)

### ISSUE THREAD

**Issue by nicolas-raoul** [Yukisama/TextLinkyTool#9]
1. Close any running instance of Firefox
2. Start `firefox -P`
3. Create a new profile
4. Go to https://addons.mozilla.org/ja/firefox/addon/copy-tab-url-we and install the extension
4. Select "moz" and press CTRL-C to copy
5. Open a new tab and type https://www.wikipedia.org then Enter
6. Go back to another tab
7. Right-click the Wikipedia tab, right-click, select `Copy Tab URL WE` > `Copy URL`
8. Open any text editor, press CTRL-V to paste
9. `moz` gets pasted. I was expecting `https://www.wikipedia.org`

Linux Ubuntu 2018.04

**Comment by Yukisama** [comment]
> Close any running instance of Firefox
>     Start firefox -P
>     Create a new profile
>     Go to https://addons.mozilla.org/ja/firefox/addon/copy-tab-url-we and install the extension
>     Select "moz" and press CTRL-C to copy
>     Open a new tab and type https://www.wikipedia.org then Enter
>     Go back to another tab
>     Right-click the Wikipedia tab, right-click, select Copy Tab URL WE > Copy URL
>     Open any text editor, press CTRL-V to paste
>     moz gets pasted. I was expecting https://www.wikipedia.org
> Linux Ubuntu 2018.04

Hi, 

Its not issue, the Mozilla security policy is not allow extensions working in "addons.mozilla.org" hosts.

the issue will close on 24 hours later.

**Comment by nicolas-raoul** [comment]
It seems to be working now with other sites indeed, thanks! :-)
